version: '3.4'

services:

  app:
    build: .
    ports:
      - 8000:8000

  keycloak-dev:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/tmp/keycloak/realm.json"
    volumes:
      - ./keycloak:/tmp/keycloak
