spring:
  main:
    allow-bean-definition-overriding: true

keycloak:
  realm: MyRealm
  auth-server-url: http://keycloak-dev:8090/auth
  resource: MyApplication
  public-client: true
  ssl-required: external
  token-store: cookie

logging:
  level:
    org.keycloak: TRACE

server:
  port: 8000
